# This rule is not used by the project app-lifecycle-kubernetes-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apps.ops.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app-lifecycle-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespacelifecyclepolicy-viewer-role
rules:
- apiGroups:
  - apps.ops.dev
  resources:
  - namespacelifecyclepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.ops.dev
  resources:
  - namespacelifecyclepolicies/status
  verbs:
  - get
