# This rule is not used by the project app-lifecycle-kubernetes-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.ops.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app-lifecycle-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespacelifecyclepolicy-admin-role
rules:
- apiGroups:
  - apps.ops.dev
  resources:
  - namespacelifecyclepolicies
  verbs:
  - '*'
- apiGroups:
  - apps.ops.dev
  resources:
  - namespacelifecyclepolicies/status
  verbs:
  - get
