apiVersion: apps.ops.dev/v1alpha1
kind: NamespaceLifecyclePolicy
metadata:
  name: nlp1
spec:
  targetNamespace: test-ns
  action: Freeze
  operationId: "op-20231215-013"
  selector:
    matchLabels:
      app: test1
  startupPolicy: Resume
  startupResumePriority: 2  # Lower priority (processed after priority 1)
  startupResumeDelay: 0s
  balancePods: true
  balanceWindowSeconds: 600